// 博客页配置文件
import { BlogCategory } from '@/types/blog';
import { BLOG_DOCS_BASE, BLOG_IMG_BASE} from '@/types/blog';

const blog_configs: BlogCategory[] = [
  {
    type: 'category',
    name: '前端',
    children: [
      {
        type: 'category',
        name: 'HTML',
        children: [
          {
            type: 'post',
            title: 'MDN文档',
            desc: 'MDN对于HTML元素的速览',
            time: '2025-7-29',
            docs: `${BLOG_DOCS_BASE}/前端/HTML/MDN.md`,
            tags: ['MDN','HTML'],
          },
        ],
      },
      {
        type: 'category',
        name: 'CSS',
        children: [],
      },
      {
        type: 'category',
        name: 'JS',
        children: [
          {
            type: 'post',
            title: 'JS中的网络请求',
            desc: '用三种方法调用cozeAPI，轮子高手',
            time: '2025-3-30',
            docs: `${BLOG_DOCS_BASE}/前端/JS/JS1.md`,
            tags: ['JS','AJAX','NET'],
          },
          {
            type: 'post',
            title: 'JS中的异步(async)',
            desc: 'JavaScript作为单线程语言，若没有异步机制，执行长时间任务时会导致整个应用响应变慢或无响应',
            time: '2025-3-30',
            docs: `${BLOG_DOCS_BASE}/前端/JS/JS2.md`,
            tags: ['JS','异步','async'],
          },
          {
            type: 'post',
            title: 'JS中的异步',
            desc: '闭包是JavaScript中一个强大的特性，也挺EX',
            time: '2025-3-30',
            docs: `${BLOG_DOCS_BASE}/前端/JS/JS3.md`,
            tags: ['JS','闭包'],
            cover: `${BLOG_IMG_BASE}/前端/JS/JS3/close1.png`,
          },
          {
            type: 'post',
            title: '语法基础这一块',
            desc: '学学JS基础，嘻嘻',
            time: '2025-3-30',
            docs: `${BLOG_DOCS_BASE}/前端/JS/JS4.md`,
            tags: ['JS','语法'],
          },
          {
            type: 'post',
            title: 'Elysia',
            desc: 'Elysia是一个轻量级的Web框架，它使用TypeScript编写，并提供了丰富的类型支持',
            time: '2025-8-13',
            docs: `${BLOG_DOCS_BASE}/前端/JS/elysia.md`,
            tags: ['Elysia','JS','Web框架'],
            cover: `${BLOG_IMG_BASE}/前端/JS/elysia/1.png`,
          },
        ],
      },
      {
        type: 'category',
        name: 'Vue',
        children: [],
      },
      {
        type: 'category',
        name: 'React',
        children: [],
      },
    ],
  },
  {
    type: 'category',
    name: '点子池',
    children: [
      {
        type: 'post',
        title: 'k3s?',
        desc: '要不要搭一个k3s呢?',
        time: '2025-6-6',
        docs: `${BLOG_DOCS_BASE}/点子池/k3s.md`,
        tags: [
          '点子',
          '小鸡',
          'k3s',
        ],
      },
    ],
  },
  {
    type: 'category',
    name: '生活',
    children: [
      {
        type: 'category',
        name: '趣事',
        children: [
          {
            type: 'post',
            title: '2025.4.5',
            desc: '张进步来了?逆天',
            time: '2025-4-5',
            docs: `${BLOG_DOCS_BASE}/生活/趣事/2025.4.5.md`,
            tags: [
              '哥们',
              '唐',
            ],
            cover: `${BLOG_IMG_BASE}/生活/趣事/2025.4.5/长江3.jpg`,
          },
        ],
      },
    ],
  },
  {
    type: 'category',
    name: '算法与数据结构',
    children: [
      {
        type: 'post',
        title: '哈夫曼',
        desc: '哈夫曼编码 & 哈夫曼树',
        time: '2025-4-10',
        docs: `${BLOG_DOCS_BASE}/算法与数据结构/哈夫曼.md`,
        tags: [
          '算法',
          '哈夫曼',
          '编码',
        ],
      },
    ],
  },
  {
    type: 'category',
    name: '配网日记',
    children: [
      {
        type: 'post',
        title: '神秘配网',
        desc: '配网日记之神秘UDP53和PROXY',
        time: '2025-9-16',
        docs: `${BLOG_DOCS_BASE}/计网/net/神秘配网.md`,
        tags: ['配网', 'UDP53', 'PROXY'],
      },
    ],
  },
  {
    type: 'category',
    name: '我爱看电影',
    children: [
      {
        type: 'post',
        title: '长安三万里',
        desc: '一部关于诗和远方的动画电影',
        time: '2025-5-29',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/长安三万里.md`,
        tags: ['动画', '历史', '诗歌'],
        cover: `${BLOG_IMG_BASE}/我爱看电影/长安三万里.png`,
      },
      {
        type: 'post',
        title: '阿凡达：水之道',
        desc: '詹姆斯·卡梅隆的科幻巨制续作',
        time: '2025-4-5',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/阿凡达-水之道.md`,
        tags: ['科幻', '视觉', '续作'],
      },
      {
        type: 'post',
        title: '白日梦想家',
        desc: '勇敢追梦的故事',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/白日梦想家.md`,
        tags: ['励志', '冒险', '成长'],
      },
      {
        type: 'post',
        title: '暴烈无声',
        desc: '悬疑犯罪题材，直击人性和社会现实',
        time: '2025-6-6',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/暴烈无声.md`,
        tags: ['悬疑', '犯罪', '人性', '社会'],
      },
      {
        type: 'post',
        title: '爆款好人',
        desc: '黑色幽默与社会讽刺',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/爆款好人.md`,
        tags: ['黑色幽默', '社会', '讽刺'],
      },
      {
        type: 'post',
        title: '海边的曼彻斯特',
        desc: '关于失去与救赎的故事',
        time: '2025-5-18',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/海边的曼彻斯特.md`,
        tags: ['家庭', '救赎', '情感'],
      },
      {
        type: 'post',
        title: '蛟龙行动',
        desc: '国产军事动作片',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/蛟龙行动.md`,
        tags: ['军事', '动作', '国产'],
      },
      {
        type: 'post',
        title: '来福大酒店',
        desc: '荒诞喜剧，人生百态',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/来福大酒店.md`,
        tags: ['喜剧', '荒诞', '人生'],
      },
      {
        type: 'post',
        title: '哪吒2之魔童闹海',
        desc: '国产动画续作',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/哪吒2之魔童闹海.md`,
        tags: ['动画', '神话', '华为'],
      },
      {
        type: 'post',
        title: '怦然心动',
        desc: '青涩纯真的爱情故事',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/怦然心动.md`,
        tags: ['爱情', '成长', '青春'],
      },
      {
        type: 'post',
        title: '让子弹飞',
        desc: '姜文导演的经典之作',
        time: '2025-4-6',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/让子弹飞.md`,
        tags: ['喜剧', '动作', '经典'],
      },
      {
        type: 'post',
        title: '狮子王2009',
        desc: '迪士尼经典动画重制',
        time: '2025-4-17',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/狮子王2009.md`,
        tags: ['动画', '经典', '迪士尼'],
      },
      {
        type: 'post',
        title: '唐探1900',
        desc: '悬疑推理题材',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/唐探1900.md`,
        tags: ['悬疑', '推理', '系列'],
      },
      {
        type: 'post',
        title: '误杀3',
        desc: '国产悬疑犯罪片',
        time: '2025-4-12',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/误杀3.md`,
        tags: ['悬疑', '犯罪', '国产'],
      },
      {
        type: 'post',
        title: '夏洛特烦恼',
        desc: '喜剧与人生选择',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/夏洛特烦恼.md`,
        tags: ['喜剧', '人生', '选择'],
      },
      {
        type: 'post',
        title: '星际穿越',
        desc: '诺兰导演的科幻巨作',
        time: '2025-5-11',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/星际穿越.md`,
        tags: ['科幻', '太空', '诺兰'],
      },
      {
        type: 'post',
        title: '也没有那么热血沸腾',
        desc: '现实与理想的碰撞',
        time: '2025-5-17',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/也没有那么热血沸腾.md`,
        tags: ['现实', '理想', '成长'],
      },
      {
        type: 'post',
        title: '遗愿清单',
        desc: '关于生命与梦想的故事',
        time: '2025-4-17',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/遗愿清单.md`,
        tags: ['生命', '梦想', '感人'],
      },
      {
        type: 'post',
        title: '这个杀手不太冷',
        desc: '经典动作片',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/这个杀手不太冷.md`,
        tags: ['动作', '经典', '情感'],
      },
      {
        type: 'post',
        title: '抓娃娃',
        desc: '温馨治愈系电影',
        time: '2025-4-2',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/抓娃娃.md`,
        tags: ['温馨', '治愈', '家庭'],
      },
      {
        type: 'post',
        title: 'The Dark Knight',
        desc: '蝙蝠侠黑暗骑士',
        time: '2025-5-9',
        docs: `${BLOG_DOCS_BASE}/我爱看电影/The_Dark_Knight.md`,
        tags: ['超级英雄', '黑暗', '诺兰'],
      },
    ],
  },
  {
    type: 'category',
    name: '我爱看番',
    children: [
      {
        type: 'post',
        title: '无职转生',
        desc: '异世界转生题材，成长与救赎',
        time: '2025-6-17',
        docs: `${BLOG_DOCS_BASE}/我爱看番/无职转生.md`,
        tags: ['异世界', '成长', '救赎'],
      },
    ],
  },
];

export default blog_configs;